import { SignInButton, useUser } from '@clerk/nextjs';
import type { NextPage } from 'next';
import Head from 'next/head';
import CreatePostWizard from '~/components/CreatePostWizard';
import Feed from '~/components/Feed';
import { api } from '~/utils/api';

const Home: NextPage = () => {
  const { isSignedIn, isLoaded } = useUser();
  api.post.getAll.useQuery();
  if (!isLoaded) return null;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen justify-center">
        <div className="flex min-h-full w-full flex-col border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-y border-slate-400 p-4">
            {isSignedIn && <CreatePostWizard />}
            {!isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
};

export default Home;
