import Head from 'next/head';
import type { ReactNode } from 'react';

interface Props {
  children: ReactNode;
}

const Layout: React.FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen justify-center">
        <div className="flex min-h-full w-full flex-col border-x border-slate-400 md:max-w-2xl">
          {children}
        </div>
      </main>
    </>
  );
};

export default Layout;
